runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 15

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 10
  success_threshold: 2
  failure_threshold: 1

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 30
  timeout_sec: 10
  success_threshold: 2
  failure_threshold: 1
  app_start_timeout_sec: 600

env_variables:
  GCP_PROJECT_ID: "jokerise"
  GCS_BUCKET: "jokerised.hyojun.me"
  TEMP_DIR: "/tmp/jokerise"
  CORS_ORIGIN: "jokerise.hyojun.me"
