runtime: custom
env: flex
network:
  instance_tag: jokeriser
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.8
