runtime: custom
env: flex

automatic_scaling:
  min_instances: 1
  max_instances: 3
  cool_down_period_sec: 600
  cpu_utilization:
    target_utilization: 0.9

resources:
  cpu: 1
  memory_gb: 1.5
  disk_size_gb: 15

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 10
  success_threshold: 2
  failure_threshold: 1

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 30
  timeout_sec: 10
  success_threshold: 2
  failure_threshold: 1
  app_start_timeout_sec: 600

env_variables:
  GCP_PROJECT_ID: "jokerise"
  GCS_BUCKET: "jokerise-results"
  TEMP_DIR: "/tmp/jokerise"
  CORS_ORIGIN: "https://jokerise.hyojun.me"
