#!/usr/bin/env bash
set -eo pipefail

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
cd "$SCRIPT_DIR" || exit 1

export HOST="0.0.0.0"
export PORT=8080
export CORS_ORIGIN="*"
export GCP_PROJECT_ID="jokerise-292915"
export GCS_BUCKET="jokerise-results-1"
export TEMP_DIR='/tmp/jokerise/'
export GOOGLE_APPLICATION_CREDENTIALS="serviceaccount.json"

env="$1"
if [[ "$env" == "gunicorn" ]]; then
  gunicorn -b "$HOST":"$PORT" main:app
else
  python main.py
fi
